"""Platform-hosted Agent identity management and delegated signing."""

from .document import (
    DID_MEDIA_TYPE,
    HOSTED_IDENTITY_DRAFT,
    WELL_KNOWN_PATH,
    create_did_document,
    create_service_scoped_agent_did,
)
from .platform import Platform
from .stores import (
    DefaultLifecyclePolicy,
    MemoryIdentityStore,
    MemoryPlatformIdempotencyStore,
    MemoryReplayStore,
)
from .types import (
    AuthorizationOperation,
    AuthorizationRequest,
    Authorizer,
    DidVerificationMethod,
    DiscoveryOptions,
    IdempotentOperation,
    IdentityListQuery,
    IdentityListResult,
    IdentityRecord,
    IdentityStore,
    KeyStore,
    LifecyclePolicy,
    PlatformIdempotencyInput,
    PlatformIdempotencyResult,
    PlatformIdempotencyState,
    PlatformIdempotencyStore,
    PlatformOptions,
    PlatformResult,
    ReplayStore,
    RequestContext,
    ServiceDidResolver,
    SignHandler,
    SignHandlerInput,
    StoredResponse,
)

__all__ = [
    "DID_MEDIA_TYPE",
    "HOSTED_IDENTITY_DRAFT",
    "WELL_KNOWN_PATH",
    "AuthorizationOperation",
    "AuthorizationRequest",
    "Authorizer",
    "DefaultLifecyclePolicy",
    "DidVerificationMethod",
    "DiscoveryOptions",
    "IdempotentOperation",
    "IdentityListQuery",
    "IdentityListResult",
    "IdentityRecord",
    "IdentityStore",
    "KeyStore",
    "LifecyclePolicy",
    "MemoryIdentityStore",
    "MemoryPlatformIdempotencyStore",
    "MemoryReplayStore",
    "Platform",
    "PlatformIdempotencyInput",
    "PlatformIdempotencyResult",
    "PlatformIdempotencyState",
    "PlatformIdempotencyStore",
    "PlatformOptions",
    "PlatformResult",
    "ReplayStore",
    "RequestContext",
    "ServiceDidResolver",
    "SignHandler",
    "SignHandlerInput",
    "StoredResponse",
    "create_did_document",
    "create_service_scoped_agent_did",
]
